CREATE TABLE pessoa (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	ativo BOOLEAN NOT NULL,
	logradouro  VARCHAR(100) NULL,
	numero VARCHAR(10) NULL,
	complemento VARCHAR(50) NULL,
	bairro VARCHAR(50) NULL,
	cep VARCHAR(10) NULL,
	cidade VARCHAR(50) NULL,
	estado VARCHAR(2) NULL	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

